[package]
name = "sqlx-migrate"
version = "0.1.0"
authors = ["Peter Frank <mdm23@gmx.de>"]
edition = "2018"

[dependencies]
sqlx-migrate-common = { path = "common" }
sqlx-migrate-macros = { path = "macros" }